ci: Add integration test coverage by source

diff --git a/.ci/integration.cloudbuild.yaml b/.ci/integration.cloudbuild.yaml
--- a/.ci/integration.cloudbuild.yaml
+++ b/.ci/integration.cloudbuild.yaml
@@ -33,7 +33,7 @@ steps:
       - name: "go"
         path: "/gopath"
     script: |
-      go test -c -race ./tests/...
+      go test -c -race -cover ./tests/...
 
   - id: "cloud-sql-pg"
     name: golang:1
@@ -54,7 +54,20 @@ steps:
     args:
       - -c
       - |
-        ./cloudsqlpg.test -test.v
+        ./cloudsqlpg.test -test.v -test.coverprofile=cloudsqlpg_coverage.out
+        export path="github.com/googleapis/genai-toolbox/internal/"
+        grep -E "^mode: |${path}sources/cloudsqlpg/|${path}tools/postgressql/|${path}tools/postgresexecutesql/"
+        cloudsqlpg_coverage.out > cloudsqlpg_coverage.out
+        
+        total_coverage=$(go tool cover -func=coverage.out | grep "total:" | awk '{print $3}')
+        echo "Cloud SQL total coverage: $total_coverage"
+        coverage_numeric=$(echo "$total_coverage" | sed 's/%//')
+        if (( $(echo "$coverage_numeric < 40" | bc -l) )); then
+            echo "Coverage failure: Cloud SQL total coverage($total_coverage) is below 40%."
+            exit 1
+        fi
+        
+
 
   - id: "alloydb-pg"
     name: golang:1
